[Variables]
Scale=1

ColorMode=1
MainColor=12,12,12
OppositeColor=255,255,255

Style=HoriMeasure
SideOrientation=Left
Brightness=150
BlurRadius=10
BlurSigma=10


WeatherLocation=Hong Kong
; Just enter your city's name or your address here or whatever. Anything should work here.
; TIP: Check Rainmeter's log to see what location it got.
WeatherUnits=Metric
; The units of the weather info. Valid values are "Metric" and "Imperial".
Language=en
