[Variables]
Scale=1
;I H
2412=I

ColorMode=1
MainColor=12,12,12
OppositeColor=255,255,255
AccentColor=255,0,0

Style=Measure

Rm.Update=25
;ArcOptions
ArcStart=(180-#ArcEnd#)
ArcEnd=30
;Tech options
ShowDetails=0
Runic=0
;Smart Options
Align=Center
Weather=1
Date=1
DateTimeRatio=0.14
Seperator=:
;Measure options
Rotation=Vert
Stroke=0
;Graph options
Circle=0
LineWidth=10

Render=Blur

;RenderBlur (Brightness, Saturation, Hue)
BlurModulate=150,100,100
BlurRadius=10
BlurSigma=2

;RenderShadow
ShadowOpacity=80
ShadowSigma=10
ShadowOffset=0,0

;RenderBar
BarBackpacity=150

WeatherLocation=Hong Kong
; Just enter your city's name or your address here or whatever. Anything should work here.
; TIP: Check Rainmeter's log to see what location it got.
WeatherUnits=Metric
; The units of the weather info. Valid values are "Metric" and "Imperial".
Language=en

Cache.Wallpaper=[WallpaperPath]
Img.W=3840
Img.H=2127
