[Title]
Text=Selected rendering mode

[Description]
Text=Rendering mode for styles

[Description2]
Meter=String
Text=Color - specify a color for filling
X=r
Y=(#sec.P#)R
FontSize=(12*#Sec.S#)
MeterStyle=Sec.String:S

[Description3]
Meter=String
Text=Shadow - draws a shadow behind contents
X=r
Y=(#sec.P#)R
FontSize=(12*#Sec.S#)
MeterStyle=Sec.String:S

[Description4]
Meter=String
Text=Blur - prerenders a blurred image of the wallpaper and masks itself to the contente
X=r
Y=(#sec.P#)R
FontSize=(12*#Sec.S#)
MeterStyle=Sec.String:S

[Description5]
Meter=String
Text="These options only apply to these styles: Center, Measure, Graph, Text"
X=r
Y=(#sec.P#)R
FontColor=255, 183, 0
FontSize=(12*#Sec.S#)
MeterStyle=Sec.String:S