[ChameleonDesktop]
Measure=Plugin
Plugin=Chameleon
Type=Desktop
[CFG1]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Foreground1
[CFG2]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Foreground2
[BG]
Measure=Plugin
Plugin=Chameleon
Parent=ChameleonDesktop
Color=Background1

[Hour]
FontColor=[CFG1]
[Hour2]
FontColor=[BG]
[ActualWave]
Fill=Fill Color [CFG2]F5
[B]
Fill=Fill Color [CFG2]1A | Stroke Color [CFG2]
DynamicVariables=1